export const CART_GET_ITEM = "CART_GET_ITEM";
export const CART_GET_ERROR = "CART_GET_ERROR";
export const CART_GET_REQUEST = "CART_GET_REQUEST";
export const CART_CLEAR_ITEMS = "CART_RESET";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
